services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes:
      - ./secrets:/config
    restart: unless-stopped

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    security_opt:
      - no-new-privileges:true
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/traefik_secret
      CF_ZONE_API_TOKEN_FILE: /run/secrets/traefik_secret
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config:/etc/traefik
    secrets:
      - traefik_secret

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - "993"
    network_mode: 'host'
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - type: bind
        source: /home/weeb/Mass_Storage
        target: /media
        read_only: true
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=jellyfin.fabiomatos999.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    environment:
      - PUID = 1000
      - PGID = 1000
      - UMASK = 002
      - TZ="America/New_York"
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/data:/data
      - /home/weeb/Mass_Storage/Downloads/complete:/downloads/complete
      - /home/weeb/Mass_Storage:/mnt
    network_mode: "service:gluetun"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes:
      - ./prowlarr/config:/config
    restart: unless-stopped

  transmission:
   image: lscr.io/linuxserver/transmission:latest
   container_name: transmission
   network_mode: "service:gluetun"
   environment:
     - PUID=1000
     - PGID=1000
     - TZ="America/New_York"
   volumes:
     - /home/weeb/Docker_Stuff/Jellyfin_Stack/transmission/conifg/config
     - /home/weeb/Mass_Storage/Downloads:/downloads
   restart: unless-stopped   

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY_FILE=/run/secrets/wireguard_private_key
      - WIREGUARD_ADDRESSES_FILE=/run/secrets/wireguard_private_key
      - SERVER_CITIES_FILE=/run/secrets/wireguard_cities
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      - 9696:9696
      - 8989:8989
    volumes:
      - ./gluetun:/gluetun
    secrets:
      - wireguard_private_key
      - wireguard_addresses
      - wireguard_cities
    restart: unless-stopped


secrets:
  traefik_secret:
    file: ./secrets/traefik-api-key.txt
  wireguard_private_key:
    file: ./secrets/wireguard-private-key.txt
  wireguard_addresses:
    file: ./secrets/wireguard-addresses.txt
  wireguard_cities:
    file: ./secrets/wireguard-cities.txt
