global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

# -- Change EntryPoints here...
entryPoints:
  http:
    address: :80
    # -- Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
certificatesResolvers:
  cloudflare:
    acme:
      email: fabio.matos999@gmail.com
      storage: /etc/traefik/certs/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 5
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# -- (Optional) Disable TLS Cert verification check
serversTransport:
  insecureSkipVerify: true

# -- (Optional) Overwrite Default Certificates
tls:
  options:
    default:
      minVersion: VersionTLS12

providers:
  docker:
    # dont expose all containers by default
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true 
